{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dicer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/diceR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/diceR/diceR_{{ version }}.tar.gz
  sha256: ad43e081a737f29fd38420301c22e6a66a79e3d89bf539ff6421cc4fd68cf188

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-abind
    - r-assertthat
    - r-class
    - r-clue
    - r-clustersim
    - r-clv
    - r-clvalid
    - r-dplyr >=0.7.5
    - r-ggplot2
    - r-infotheo
    - r-klar
    - r-magrittr
    - r-mclust
    - r-nmf
    - r-purrr >=0.2.3
    - r-rankaggreg
    - r-rcpp
    - r-stringr
    - r-tidyr
    - r-yardstick
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-abind
    - r-assertthat
    - r-class
    - r-clue
    - r-clustersim
    - r-clv
    - r-clvalid
    - r-dplyr >=0.7.5
    - r-ggplot2
    - r-infotheo
    - r-klar
    - r-magrittr
    - r-mclust
    - r-nmf
    - r-purrr >=0.2.3
    - r-rankaggreg
    - r-rcpp
    - r-stringr
    - r-tidyr
    - r-yardstick

test:
  commands:
    - $R -e "library('diceR')"           # [not win]
    - "\"%R%\" -e \"library('diceR')\""  # [win]

about:
  home: https://alinetalhouk.github.io/diceR/
  dev_url: https://github.com/AlineTalhouk/diceR/
  license: MIT
  summary: Performs cluster analysis using an ensemble clustering framework, Chiu & Talhouk (2018) <doi:10.1186/s12859-017-1996-y>.  Results from a diverse set of algorithms are pooled together using methods such as majority voting, K-Modes, LinkCluE, and CSPA. There are options to compare cluster assignments across algorithms
    using internal and external indices, visualizations such as heatmaps, and significance testing for the existence of clusters.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
